-- Configures the nvim-treesitter plugin.
-- Defines the list of parsers to be installed for syntax highlighting.

local options = {
  ensure_installed = {
    "bash",
    "bibtex",
    "c",
    "cmake",
    "cpp",
    "css",
    "cuda",
    "dockerfile",
    "fish",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "glsl",
    "go",
    "gomod",
    "gosum",
    "gotmpl",
    "graphql",
    "hcl",
    "helm",
    "hlsl",
    "html",
    "hyprlang",
    "javascript",
    "json",
    "json5",
    "jsonc",
    "julia",
    "lua",
    "luadoc",
    "make",
    "markdown",
    "nginx",
    "nix",
    "proto",
    "python",
    "rust",
    "solidity",
    "sql",
    "ssh_config",
    "terraform",
    "textproto",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
    "zig",
  },
  highlight = {
    enable = true,
  },
}

return options
