general {
  hide_cursor = true
}

background {
  path = screenshot
  blur_passes = 3
  blur_size = 7
  brightness = 0.5
  contrast = 0.9
}

label {
  text = $TIME
  font_size = 64
  font_family = JetBrains Mono
  position = 0, 80
  halign = center
  valign = center
}

label {
  text = cmd[update:60000] date "+%A, %B %d"
  font_size = 18
  font_family = JetBrains Mono
  position = 0, 10
  halign = center
  valign = center
}

input-field {
  size = 300, 56
  position = 0, -80
  halign = center
  valign = center
  rounding = 8
  placeholder_text = <i>Password</i>
  fail_text = $FAIL ($ATTEMPTS)
  hide_input = false
  check_color = rgba(249, 226, 175, 1.0)
  fail_color = rgba(243, 139, 168, 1.0)
}
