general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 240
  on-timeout = hyprctl workspaces -j | grep -q '"hasfullscreen": true' || (brightnessctl -s set 10% && touch "$XDG_RUNTIME_DIR/hypridle_dimmed")
  on-resume = [ -f "$XDG_RUNTIME_DIR/hypridle_dimmed" ] && (brightnessctl -r && rm "$XDG_RUNTIME_DIR/hypridle_dimmed")
}

listener {
  timeout = 300
  on-timeout = hyprctl workspaces -j | grep -q '"hasfullscreen": true' || loginctl lock-session
}

listener {
  timeout = 600
  on-timeout = hyprctl workspaces -j | grep -q '"hasfullscreen": true' || hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}
