[settings]
auto_install = false
activate_aggressive = true
windows_default_inline_shell_args = "bash -c"

[settings.github]
credential_command = "gh auth token"

[settings.npm]
package_manager = "aube"

[tasks."setup:go-telemetry"]
description = "Disable Go telemetry"
run = """
go telemetry off
test "$(go telemetry)" = "off"
"""

# [tasks.setup]
# description = "Apply safe, idempotent global mise setup"
# depends = ["setup:go-telemetry"]
