[tool_alias]
nushell = "aqua:nushell/nushell"

[tools]
carapace = "1.7.3"
just = "1.57.0"
nushell = "0.114.1"
powershell = "7.6.4"
starship = "1.26.0"
vendir = "0.46.0"

# TODO: FIX ME
# direnv = "2.37.1"
# usage = "4.0.0"
# "cargo:dotter" = "0.13.5"
