[tools]
# NOTE: https://context7.com/
"npm:ctx7" = "0.5.6"
"npm:@upstash/context7-mcp" = "3.2.5"

# NOTE: https://playwright.dev
"npm:@playwright/mcp" = "0.0.78"
"npm:@playwright/cli" = "0.1.17"

"npm:@eargollo/vikunja-mcp" = { version = "1.2.1", allow_low_downloads = true }

# NOTE: https://oraios.github.io/serena
"pipx:serena-agent" = "1.6.1"

# NOTE: https://graphify.com/
"pipx:graphifyy[mcp]" = "0.9.28"
"pipx:graphifyy" = "0.9.29"
